language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "search-bar:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: uxDBfM8r1FWVGQULQVQxsup+tXx/mTIZ6eN40rwGmfYjHSLplcsdzjnyxpXCZIFWqk50O/HfcgCX7gva5TPzshaDYaZLiuYipjxgQm5s+qDJGZ83pHaLO54FX6dDaJaWqCeK+Re7P2iXqUfVTUeNMDP46jBP+obBFprpircC0pa8mbHIRsHzc3R7Hs/gSlbcvmuTPExJQYX63eTndJtX8m/UZ8bYG7kFfTmvGfmUmfIf0/IlNdlyKgpk0MbqnMtMyUTfcB4+IrXkvY18eRkT2rcEMTPCVvzc3MRIJp1dv43fUD+ImUL9p4PuF9sjMNEF5WQAr6iX+g95iLZkACh8QLVQC4VhjaPCcTKi6oezPwRJKkxmDdsoTC0qbBMdFPDrhioA+05ZiM0c1iUlFA+pC0Is4zm53fKX98Uau7HNPZ6164zrZl6lbaupDguCwp6z17Z3nNoO0fjvJMlM+GyS33iHKQk0fccSGwZUiWFZNCQs5s8nnKkoZmBkSsVrR5lx6K6vz8fXW5Jdd0lf9rsgDOsPFzjabq+vo145UDkWl66AdS7z3IZFWNjIVmDJOBMQ1IA5dQXj9Fd5m20NPROJplPVLbkK6Yoiz7DjTK35WvJtHPeSEpKVVIEA0oIHqhU8CyIbn5JWUGRrfwZOPXIcRD8cyQPcVxnC6GDcklS7pcg=
  - secure: vjkVrGdctwc88d6kHZCGxFzgNc1XzJmERpqBHTYqtd5fviH3t82cTHB6m2kwy+nRpkneefOyqcRh0RTfk9lMLMHjYB/y0pm7W7IJgpH9hAqCo6e9J1MBQ5NmOdHBYpD8NEq+xrS2Fo8rROmzCkyMo6IJNdL4RGI83hLWL5PzkTVfHR0dhFFyfbe5kbK5FGuFmFmeu3XJQlnPyr8m6lksIfW7WzZ+ye2x/OhzkucjYu7d9RpktS8faNhe1CtjzWM6MxJ5V0NNE4ggM9PI/bYPXO0Rh4UpxoeG9TnxoZq4ZqkrU/Z0bevOjDDtrp21+3muuCIsYYxDYfLljW22wm2aY3SPWnV5juyjazFYnXKAKERuHuBXRG8tKF6HI7gLR4GNJKm2O+u4dGGXm05W+XSJ5YUd6cMYfAHXMzQNWyoqLKMZGNSuhxFcpM+VJ6sseGR9QhyFmY97Itho135oSrkkgrPQIuCyp5kDIM2WYFKw9rMkTwdAGwEFLwkTEv49ni40KL1ZuPi4m1AqEGck8mRk/7vOxejE0XBELYcdNEgRSAkHXDWDZK/3qRlp18fDEmmI2oj5eLrD6S3+f9TDmpwJBggShk6jzwWmumfAIzlBF3NG/KSsxppjqpu1+x57ZYINQAu5Dx4TjIyevlqEGLubNk5tWVT8slxJAK/QN4vjn3k=
